### ISSUE TITLE
how to import react-bootstrap-select, not require

### ISSUE THREAD

**Issue by shaunthegeek** [tjwebb/react-bootstrap-select#13]
docs say "require", like:

```
React = require('react');
React.Bootstrap = require('react-bootstrap');
React.Bootstrap.Select = require('react-bootstrap-select');
```

how can I import it in fluxible web app, I use this but failed:

```
npm install react-bootstrap-select react-bootstrap --save

import React from 'react';
import { jQuery } from 'jquery';
import { Bootstrap } from 'react-bootstrap';
import Select from 'react-bootstrap-select';

class Demo extends React.Component {
    render() {
         return (
        <Select>
           <option>Mustard</option>
           <option>Ketchup</option>
           <option>Barbecue</option>
        </Select>
        );
    }
}
```

`npm run dev` show error:

```
> node index_dev

/home/ubuntu/code/web-app/node_modules/react-bootstrap-select/js/bootstrap-select.js:1373
})(jQuery);
   ^

ReferenceError: jQuery is not defined
    at Object.<anonymous> (/home/ubuntu/code/web-app/node_modules/react-bootstrap-select/js/bootstrap-select.js:1373:4)
    at Module._compile (module.js:397:26)
    at Module._extensions..js (module.js:404:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ubuntu/code/web-app/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/code/web-app/node_modules/react-bootstrap-select/dist/Select.js:4:1)
    at Module._compile (module.js:397:26)
```

then I install jquery, then it show the same error.

```
npm install jquery --save
```

**Comment by tjwebb** [comment]
I don't know what fluxible is. When you figure it out, a PR is welcome.

**Comment by Godefroy** [comment]
I've got the exact same problem on a simple React app.

**Comment by wlopata** [comment]
I run into exact same error, and since I'm building with webpack [that solution](http://stackoverflow.com/a/31253593/1818783) worked for me. There are some other answers that don't require using webpack, I haven't tried them though.
